### AUTH

### Create a new account
POST http://localhost:3333/users
Content-Type: application/json
 
{
  "name": "Teste",
  "email": "hugoxvida@gmail.com",
  "password": "romerito"
}

### Authenticate with e-mail & password
POST http://localhost:3333/sessions/password
Content-Type: application/json
 
{
  "email": "hugoxvida@gmail.com",
  "password": "romerito"
}

### Get authenticate user profile
GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NDAwOGNmMS1jNjVlLTRlNmItODU5YS1iYWU0Zjk5MzQ4NzgiLCJpYXQiOjE3NTE5MTM0NTIsImV4cCI6MTc1MjUxODI1Mn0.qFt8bgceX9meQ1uK_An5c_UAw78ad5gp-7eBBvBNQQw

### Teste de autenticação com Google OAuth
POST http://localhost:3333/sessions/google
Content-Type: application/json

{
  "code": "4/0AQSTgQGPsgqDN05cvb5cgSYWTYUe9HMzPbkn0Ia_bJtJVZgYnQagboDoFzjNLJ72MRNyfQ"
}

### 

POST http://localhost:3333/password/recover
Content-Type: application/json

{
  "email": "hugoxvida@gmail.com"
}

















### Teste de autenticação com Google OAuth
POST http://localhost:3333/organizations/equipe-ea/units/teste/invites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjViY2Q0Yi01YTM5LTQ4NDMtYWNmNS1lYzdiMWY2NWIyMjciLCJpYXQiOjE3NDMzNzgxODEsImV4cCI6MTc0Mzk4Mjk4MX0.8aJxka7PyNjraL2zeyKtVnvm7wXSoahCyhcCDaDQbDI

{
  "email": "hugoxvida@gmail.com",
  "role": "ADMIN"
}

### Obter URL de autenticação do Google
GET http://localhost:3333/auth/google/url

###


GET http://localhost:3333/organizations/equipe-ea/units
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjViY2Q0Yi01YTM5LTQ4NDMtYWNmNS1lYzdiMWY2NWIyMjciLCJpYXQiOjE3NDI5NTg3ODMsImV4cCI6MTc0MzU2MzU4M30.ZNd7409DcqUNy8aCDhCA3ySaWxBhFXX63_9J97Tjzt4



###


GET http://localhost:3333/organizations/equipe-ea/units/teste/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjViY2Q0Yi01YTM5LTQ4NDMtYWNmNS1lYzdiMWY2NWIyMjciLCJpYXQiOjE3NDI5NTg3ODMsImV4cCI6MTc0MzU2MzU4M30.ZNd7409DcqUNy8aCDhCA3ySaWxBhFXX63_9J97Tjzt4



###


POST http://localhost:3333/invites/cb1dc80b-e4af-48f7-9e77-0f98cbd5bbc3/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTk1YzYxMC1lYTJiLTRhZTMtYmE4NS1mMjI2OGI2ZWZmOTAiLCJpYXQiOjE3NDIzOTQ4NTUsImV4cCI6MTc0Mjk5OTY1NX0.X2RliSz5NFb4s52Tj0Zg-lEgvlFgc-MoMq13UFOf1-A


###


PATCH http://localhost:3333/organizations/equipe-ea/units/teste/demands/ed0b4e0e-053b-47b4-ac01-ed617a8ac305
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjViY2Q0Yi01YTM5LTQ4NDMtYWNmNS1lYzdiMWY2NWIyMjciLCJpYXQiOjE3NDMzNzgxODEsImV4cCI6MTc0Mzk4Mjk4MX0.8aJxka7PyNjraL2zeyKtVnvm7wXSoahCyhcCDaDQbDI

{
  "status": "IN_PROGRESS"
}

###


GET https://api.pexels.com/v1/search?query=music
Content-Type: application/json
Authorization: tuFISvxpU98P7GOZMKtWDPQhqXb0WzcAAyFWDzEMZoteQtu9jfh8jhdL
